# Generated by Django 3.2.7 on 2021-09-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('quanity', models.IntegerField(default=0)),
                ('image', models.URLField(default='')),
            ],
        ),
    ]
