# Generated by Django 3.2.7 on 2021-10-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211006_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bookId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
