# Generated by Django 3.2.7 on 2021-10-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211006_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('quanity', models.IntegerField(default=0)),
                ('image', models.URLField(default='')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('quanity', models.IntegerField(default=0)),
                ('image', models.URLField(default='')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
