# Generated by Django 3.2.7 on 2021-10-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211007_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quanity',
        ),
    ]
