# Generated by Django 3.2.7 on 2021-10-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_orderitem_quanity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quanity',
            field=models.IntegerField(default=1),
        ),
    ]
